[DRAFT] Nkr/fc/service social
Neighbook/Backend pull request #15
Opened 2023-01-18 10:56 UTC by Kroissan

Les ***issues*** sont rédigées en markdown. GitHub à écrit un bon résumer de comment se servir du
markdown [ici](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf).

## Prérequis

***Cette partie est juste là pour vous rappeler les prérequis avant de créer une pull request, vous pouvez la supprimer
avant sa création***

Merci pour votre contribution :heart:. Avant de créer la **pull request** merci d'avoir vérifié que vous remplissez
toutes les conditions de la partie ["Liste de vérification"](#Checks). De surcroît, merci de vérifier que vous avez bien
remplis toutes les parties qui suivent et que vous respectez les règles de titre ceci rend le travail des **reviewer**
plus simples :heart:.

### Titre des "pull request" :

Votre titre de **pull request** doit contenir un libellé ainsi qu'une description brève. Les libellés doivent être
pertinents et minimaliste, voici une liste non exhaustive :

- [BOGUE] : Bogue réglé.
- [FONCTIONNALITÉ] : Ajout d'une nouvelle fonctionnalité.
- [CASSE] : Ajouté ce libellé pour toute PR qui casserai la rétro compatibilité.
- [DOCUMENTATION] : mise à jour de la documentation.

Exemple de titre : `[BOGUE] Les morceaux d'annanas sur la pizza ont été enlevés`

## 1) Description

Merci d'inclure un résumé des changements et des **issue** en relation avec la PR. De plus, ajouter la motivation de
cette **pull request** ainsi que le contexte. N'oubliez pas de lister toutes les dépendances nécessaires pour que ce
changement soit effectif.

## 2) Choix technique

Pourquoi avez-vous choisi cette méthode d'implémentation ? Pourquoi pas une autre ?

## 3) Liste de vérification

- [ ] Mon code suit les règles de contribution.
- [ ] J'ai lu le code de conduite.
- [ ] J'ai effectué une relecture de mon code.
- [ ] Mes changements n'impliquent pas de nouvelles erreurs ou avertissements.
- [ ] Les tests unitaires (nouveaux et anciens) passe localement avec mes nouveaux changements.

2023-02-06 13:28 UTC, Kroissan commented
close #16 #19 #20 #21 #22

2023-02-06 14:19 UTC, follyjohn requested changes
Juste quelques changement mineurs

2023-02-06 14:19 UTC, follyjohn commented on package.json
> +		"yarn": "^1.22.19"
Y a pas à mettre yarn commme dépendance

2023-02-06 14:19 UTC, follyjohn commented on src/core/datastores/typeorm_datastores.ts
> +  synchronize: true,
Voir user data store pour la config ssl et loging

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Abonnement.ts
> +    id!: number;
@PrimaryGeneratedColumn('uuid')
id!: string;

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Block.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Comment.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Evenement.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Follow.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Image.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Post.ts
> +    id!: number;
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Post.ts
> +    ncommentaires!: number;
Column() ?

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/PostReaction.ts
> +    id!: number;
les id : 
@PrimaryGeneratedColumn('uuid')
id!: string;

2023-02-06 14:19 UTC, follyjohn commented on src/services/social/block_service.ts
> +                console.log('Error: ' + error);
throw new ServiceException

2023-02-06 14:19 UTC, follyjohn commented on src/services/social/block_service.ts
> +                 console.log('Error: ' + error);
Same

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
On peut diminuer la complexité : 

```js
if (!req.query.id) {
    res.status(400).json('provide id');
}
const searchId = Number(req.query.id);
const comments = await CommentService.getComment(searchId);
if (comments == null) {
    res.status(404).send();
}
```

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem ca t'evite des else

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +		res.status(400).json('invalid fields');
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +});
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem, et verifie chaque field avec un if distinct

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +		res.status(400).send();
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +});
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +});
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +		res.status(400).json('invalid fields');
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +	}
Idem

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +export const socialRoutes = _socialRoutes;
on peut declarer const socialRoutes = Router();

et finir avec export { socialRoutes }

2023-02-06 14:19 UTC, follyjohn commented on src/api/routes/social/social_routes.ts
> +export const _socialRoutes = express.Router();
export const socialRoutes = express.Router();

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Abonnement.ts
> +	id!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Block.ts
> +	idUtilisateur!: string;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Block.ts
> +}
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Comment.ts
> +	id!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Evenement.ts
> +	id!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Image.ts
> +	id!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/Post.ts
> +	id!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/models/social/PostReaction.ts
> +	reactionId!: number;
```js
@PrimaryGeneratedColumn('uuid')
id!: string;
```

2023-02-06 14:19 UTC, follyjohn commented on src/services/social/block_service.ts
> +				logger.error(error);
```js
throw new ServiceException(...
```

2023-02-06 14:19 UTC, follyjohn commented on src/services/social/follow_service.ts
> +			});
```js
throw new ServiceException(...
```

2023-02-07 08:32 UTC, follyjohn approved these changes
ok 👍

2023-02-07 08:32 UTC, follyjohn commented
Met a jour le commentaire de PR

2023-02-07 13:00 UTC, merged